#42 add deck definition
GingaaBread/GitHub-Game-Off-23 pull request #10
Opened 2023-11-12 06:20 UTC by Leo-gp

2023-11-12 15:10 UTC, GingaaBread requested changes

2023-11-12 15:10 UTC, GingaaBread commented on Assets/Scripts/main/repository/Card Management/Deck Definition/ResourceDeckDefinitionRepository.cs
> +            LocalizationSettings.SelectedLocale = LocalizationSettings.ProjectLocale; // TODO: Remove
What is this? :)

2023-11-12 15:10 UTC, GingaaBread commented on Assets/Scripts/main/service/Card Management/CardPoolService.cs
> +        //private readonly CardPool _cardPool = new();
Where is the new card pool?

2023-11-12 15:22 UTC, Leo-gp commented on Assets/Scripts/main/repository/Card Management/Deck Definition/ResourceDeckDefinitionRepository.cs
> +            LocalizationSettings.SelectedLocale = LocalizationSettings.ProjectLocale; // TODO: Remove
This is from the first commit of this PR, it was just for testing purposes, it's not there anymore.

2023-11-12 15:31 UTC, Leo-gp commented on Assets/Scripts/main/service/Card Management/CardPoolService.cs
> +        //private readonly CardPool _cardPool = new();
My bad, I forgot to uncomment stuff here, I'll keep it as it was (and `GameTests ` will pass again). Thanks for pointing out. I may do some rework in `CardPoolService` and `DeckService` for the next task, given the changes on this PR. With that I'll also remove the deck definition legacy classes (as I renamed them).

2023-11-13 03:09 UTC, GingaaBread approved these changes

2023-11-13 03:09 UTC, merged