#37 implement card effects
GingaaBread/GitHub-Game-Off-23 pull request #14
Opened 2023-11-17 01:41 UTC by samoncrief

Base scripts for card effect SOs including variables.

2023-11-17 20:24 UTC, GingaaBread requested changes

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/service/Turn System/EffectAssemblyService.cs
> +            _effectAssembly.Effects.ForEach(effect => effect.effectBase.Execute(effect.multiplier));
This should rename effect to effectInPlay since it is not an object of CardEffect any more.
This can also be nicer if we add a method to the CardEffectInPlay entity, which calls its stored effect with its multiplier.
So here, there would just be `effectInPlay.Execute()` with no parameter.

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/TimeReductionCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/TimeReductionCE.cs
> +        [SerializeField] private int _halfAmountInstead;
I just saw that this is wrong in the diagram. This should be a bool, of course

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/TimeReductionCE.cs
> +        [SerializeField] private CardClass requiredCardClass;
underscore naming convention

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/TimeGainCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/TimeBuffWhileOnBoardCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishWithTimeBonusCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishWithItemOnBoardBonusCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishWithHandCardSizeBonusCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishMultipliedCE.cs
> +        //public Card playedCardRef;
This should be serialised too

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishMultipliedCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishCE.cs
> +        [SerializeField] private CardClass _classToAffect;
What about this? This isn't in the diagram, right?

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishCE.cs
> +        [SerializeField] private ItemCard _asLongAsItemOnBoard;
What about this? This isn't in the diagram, right?

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleBuffCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishCE.cs
> +        [SerializeField] private CardClass _classToAffect;
Ah I think it's a remainder from copying from the class above

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishCE.cs
> +        [SerializeField] private ItemCard _asLongAsItemOnBoard;
Remainder from copy and paste, this should be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleAllFishThisTurnCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/PreventDiscardCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/IncreaseCardsDrawnCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/IncreaseAllIBoardtemCountersCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/DrawCardCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Effects/DoubleEffectCE.cs
> +        private string _message;
This can be removed

2023-11-17 20:24 UTC, GingaaBread commented on Assets/Scripts/main/entity/Card Management/Card Data/CardEffectInPlay.cs
> +using NaughtyAttributes;
Why is this needed?

2023-11-18 01:37 UTC, samoncrief commented on Assets/Scripts/main/entity/Card Management/Card Data/CardEffectInPlay.cs
> +using NaughtyAttributes;
> Why is this needed?

Holdover from the file I based it on, I'll remove it

2023-11-18 01:42 UTC, samoncrief commented on Assets/Scripts/main/entity/Card Management/Card Effects/ScaleFishCE.cs
> +        [SerializeField] private CardClass _classToAffect;
Oh, that, I originally missed this effect in the diagram and copied another class in as a base, I'll remove it

2023-11-18 14:39 UTC, GingaaBread approved these changes

2023-11-18 14:40 UTC, merged